<a href="https://colab.research.google.com/github/runtorain/ComputerVision/blob/main/CNN_Weigth_bias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# Define the convolutional layer
conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)

# Print the randomly initialized filters (weights)
print("Shape of filters:", conv1.weight.shape)  # (32, 3, 3, 3)
print("Filters (randomly initialized):")
print(conv1.weight)  # Weights for all 32 filters


Shape of filters: torch.Size([32, 3, 3, 3])
Filters (randomly initialized):
Parameter containing:
tensor([[[[ 2.5079e-02, -9.0963e-02, -1.8949e-01],
          [-7.1258e-02, -1.7488e-01, -1.6520e-01],
          [ 7.2717e-02, -1.8296e-01, -1.0058e-01]],

         [[ 1.5633e-01, -1.2537e-01, -1.0939e-01],
          [ 2.0560e-02, -1.0566e-01, -1.8585e-01],
          [-1.0833e-01, -1.3430e-01, -1.4645e-02]],

         [[ 1.2198e-01,  5.2048e-02, -3.7096e-02],
          [-7.9642e-02,  1.4960e-01, -6.4124e-02],
          [-1.1397e-01,  1.5131e-01, -6.6961e-02]]],


        [[[ 6.6728e-02, -1.6670e-01,  1.2657e-01],
          [-4.5617e-02,  1.5045e-01, -1.3322e-01],
          [ 1.4935e-01, -1.6350e-02,  1.6296e-01]],

         [[-8.2114e-02, -1.4286e-01,  1.8837e-01],
          [ 3.7482e-02, -1.8193e-01,  8.1844e-02],
          [ 1.4520e-01,  3.3752e-04,  8.1485e-02]],

         [[ 7.9023e-02, -1.2222e-01, -1.5634e-01],
          [-6.0534e-02, -1.6675e-01,  1.7216e-01],
          [-1.6540e-01,

In [ ]:
# Get the first filter
first_filter = conv1.weight[0]
print("First filter (shape):", first_filter.shape)  # (3, 3, 3)
print(first_filter)  # Weights for the first filter


First filter (shape): torch.Size([3, 3, 3])
tensor([[[ 0.0251, -0.0910, -0.1895],
         [-0.0713, -0.1749, -0.1652],
         [ 0.0727, -0.1830, -0.1006]],

        [[ 0.1563, -0.1254, -0.1094],
         [ 0.0206, -0.1057, -0.1858],
         [-0.1083, -0.1343, -0.0146]],

        [[ 0.1220,  0.0520, -0.0371],
         [-0.0796,  0.1496, -0.0641],
         [-0.1140,  0.1513, -0.0670]]], grad_fn=<SelectBackward0>)


In [ ]:
conv1.weight[1]

tensor([[[ 0.0667, -0.1667,  0.1266],
         [-0.0456,  0.1505, -0.1332],
         [ 0.1493, -0.0164,  0.1630]],

        [[-0.0821, -0.1429,  0.1884],
         [ 0.0375, -0.1819,  0.0818],
         [ 0.1452,  0.0003,  0.0815]],

        [[ 0.0790, -0.1222, -0.1563],
         [-0.0605, -0.1667,  0.1722],
         [-0.1654, -0.1556,  0.1049]]], grad_fn=<SelectBackward0>)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the model
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):  # Adding num_classes for better usability
        super(SimpleCNN, self).__init__()

        # Convolutional layers with BatchNorm and LeakyReLU
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1, stride=1)
        self.bn1 = nn.BatchNorm2d(32)

        self.conv2 = nn.Conv2d(32, 32, kernel_size=3, padding=1, stride=2)
        self.bn2 = nn.BatchNorm2d(32)

        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1, stride=1)
        self.bn3 = nn.BatchNorm2d(64)

        self.conv4 = nn.Conv2d(64, 64, kernel_size=3, padding=1, stride=2)
        self.bn4 = nn.BatchNorm2d(64)

        # Fully connected layers
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, num_classes)

        # Dropout layer
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = F.leaky_relu(self.bn1(self.conv1(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn2(self.conv2(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn3(self.conv3(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn4(self.conv4(x)), negative_slope=0.01)

        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = F.leaky_relu(self.fc1(x), negative_slope=0.01)
        x = self.dropout(x)
        x = self.fc2(x)

        return F.softmax(x, dim=1)




In [ ]:
# Instantiate the model
model = SimpleCNN(num_classes=10)

# Access weights of conv2
conv2_weights = model.conv2.weight
print("conv2 weights shape:", conv2_weights.shape)
print("conv2 weights:", conv2_weights)


conv2 weights shape: torch.Size([32, 32, 3, 3])
conv2 weights: Parameter containing:
tensor([[[[ 0.0260,  0.0302,  0.0518],
          [-0.0223, -0.0367,  0.0468],
          [ 0.0549, -0.0265,  0.0479]],

         [[ 0.0444, -0.0227, -0.0506],
          [-0.0237,  0.0488, -0.0011],
          [-0.0317, -0.0572, -0.0502]],

         [[-0.0551, -0.0022, -0.0337],
          [-0.0555,  0.0087,  0.0232],
          [ 0.0178, -0.0012,  0.0321]],

         ...,

         [[ 0.0304,  0.0554, -0.0447],
          [-0.0239, -0.0066, -0.0468],
          [ 0.0311, -0.0275, -0.0114]],

         [[-0.0134, -0.0546, -0.0445],
          [-0.0348,  0.0162, -0.0067],
          [-0.0579, -0.0192,  0.0495]],

         [[ 0.0247, -0.0384,  0.0456],
          [ 0.0089,  0.0028,  0.0005],
          [-0.0332,  0.0426,  0.0115]]],


        [[[ 0.0524, -0.0292, -0.0069],
          [-0.0344,  0.0449, -0.0435],
          [ 0.0448, -0.0082, -0.0133]],

         [[-0.0332, -0.0302, -0.0247],
          [ 0.0112,  0.055

In [ ]:
# Access the bias of conv2
conv2_bias = model.conv2.bias

# Print the shape of the bias
print("conv2 bias shape:", conv2_bias.shape)

# Print the bias values
print("conv2 bias:", conv2_bias)


conv2 bias shape: torch.Size([32])
conv2 bias: Parameter containing:
tensor([-0.0309, -0.0123,  0.0194,  0.0163,  0.0280,  0.0118,  0.0289,  0.0069,
        -0.0034, -0.0568, -0.0344,  0.0184,  0.0404, -0.0546, -0.0442,  0.0514,
         0.0569, -0.0418,  0.0310, -0.0346, -0.0437, -0.0234,  0.0474, -0.0164,
         0.0467, -0.0536, -0.0377,  0.0493, -0.0491, -0.0320,  0.0411,  0.0361],
       requires_grad=True)


In [ ]:
# Access weights of bn2
bn2_weights = model.bn2.weight
print("bn2 weights shape:", bn2_weights.shape)
print("bn2 weights:", bn2_weights)


bn2 weights shape: torch.Size([32])
bn2 weights: Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)


In [ ]:
# Access biases of bn2
bn2_biases = model.bn2.bias
print("bn2 biases shape:", bn2_biases.shape)
print("bn2 biases:", bn2_biases)

bn2 biases shape: torch.Size([32])
bn2 biases: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)


In [ ]:
bn2_beta = model.bn2.bias
print("bn2 beta shape:", bn2_beta.shape)
print("bn2 beta:", bn2_beta)


bn2 beta shape: torch.Size([32])
bn2 beta: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)


In [ ]:
fc1_bias = model.fc1.bias
print("fc1 bias shape:", fc1_bias.shape)
print("fc1 bias:", fc1_bias)

fc1 bias shape: torch.Size([128])
fc1 bias: Parameter containing:
tensor([-0.0132,  0.0007,  0.0094,  0.0002, -0.0146, -0.0110,  0.0026,  0.0028,
        -0.0128, -0.0035,  0.0012, -0.0109, -0.0005, -0.0136, -0.0150, -0.0071,
        -0.0137, -0.0140,  0.0137, -0.0141, -0.0012,  0.0027, -0.0050,  0.0132,
        -0.0139,  0.0099, -0.0056,  0.0065, -0.0107, -0.0086, -0.0014, -0.0131,
        -0.0107,  0.0082,  0.0138, -0.0155, -0.0062, -0.0019,  0.0003, -0.0113,
        -0.0127, -0.0093,  0.0062,  0.0002, -0.0078, -0.0078,  0.0106, -0.0082,
         0.0037, -0.0005, -0.0053,  0.0038, -0.0011, -0.0019, -0.0072,  0.0129,
        -0.0150, -0.0053, -0.0066,  0.0124, -0.0066,  0.0134, -0.0041,  0.0152,
         0.0111, -0.0154,  0.0129, -0.0010,  0.0082, -0.0112,  0.0048, -0.0013,
        -0.0145,  0.0047,  0.0096, -0.0080, -0.0098, -0.0099,  0.0009,  0.0124,
        -0.0115, -0.0080,  0.0114, -0.0020,  0.0125, -0.0053,  0.0091,  0.0081,
         0.0016,  0.0085,  0.0058,  0.0040,  0.0085,  

In [ ]:
fc2_bias = model.fc2.bias
print("fc1 bias shape:", fc2_bias.shape)
print("fc1 bias:", fc2_bias)

fc1 bias shape: torch.Size([10])
fc1 bias: Parameter containing:
tensor([ 0.0090,  0.0360,  0.0302, -0.0020, -0.0877,  0.0639, -0.0396,  0.0170,
        -0.0614, -0.0517], requires_grad=True)


In [ ]:
fc2_weight = model.fc2.weight
print("fc1 weight shape:", fc2_weight.shape)
print("fc1 weight:", fc2_weight)

fc1 weight shape: torch.Size([10, 128])
fc1 weight: Parameter containing:
tensor([[ 0.0346, -0.0281, -0.0768,  ...,  0.0100, -0.0729, -0.0465],
        [ 0.0312, -0.0665,  0.0349,  ..., -0.0477,  0.0597,  0.0490],
        [ 0.0731,  0.0326,  0.0414,  ..., -0.0145,  0.0511,  0.0615],
        ...,
        [-0.0429, -0.0847,  0.0782,  ...,  0.0308, -0.0855, -0.0507],
        [ 0.0191, -0.0075, -0.0361,  ...,  0.0768, -0.0878, -0.0458],
        [ 0.0239,  0.0773, -0.0394,  ...,  0.0866,  0.0205, -0.0201]],
       requires_grad=True)
